version: 3

tasks:
  bump:
    vars:
      VERSION:
        sh: yq '.project.version' pyproject.toml
    cmds:
      - cmd: git --git-dir=./dprint/.git checkout {{ .VERSION }}
      - cmd: git add ./dprint/
      - cmd: git add pyproject.toml
      - cmd: 'git commit -m "release: v{{ .VERSION }}"'
      - cmd: git tag "v{{ .VERSION }}" -m "v{{ .VERSION }}"
      - cmd: git push
