name: build wheels

on:
  workflow_call:

jobs:
  wheels:
    runs-on: "ubuntu-24.04"
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive

      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - uses: astral-sh/setup-uv@v6
        with:
          activate-environment: true

      - run: uv sync --locked

      - run: python build.py

      - uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: dist
