name: build wheels

on:
  workflow_call:

jobs:
  wheels:
    runs-on: "ubuntu-24.04"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5
        with:
          python-version: "3.12"

      - run: pip install -r requirements.txt
      - run: python build.py

      - uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: dist
