name: build wheels

on:
  workflow_call:

jobs:
  wheels:
    runs-on: "ubuntu-24.04"
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          submodules: recursive

      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: "3.12"

      - uses: astral-sh/setup-uv@v6
        with:
          activate-environment: true

      - run: uv sync --locked

      - run: python build.py

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: wheels
          path: dist
