name: build wheels

on:
  workflow_call:

jobs:
  wheel:
    name: ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: windows-latest
            target: x64
            name: "windows x64"

          - runner: macos-13
            target: x86_64
            name: "macos x64"

          - runner: macos-14
            target: aarch64
            name: "macos arm64"

          - runner: ubuntu-24.04
            target: x64
            manylinux: auto
            name: "linux x64 glibc"

          - runner: ubuntu-24.04-arm
            target: aarch64
            manylinux: auto
            name: "linux arm64 glibc"

          - runner: ubuntu-24.04
            target: x64
            manylinux: musllinux_1_2
            name: "linux x64 musl"

          - runner: ubuntu-24.04-arm
            target: aarch64
            manylinux: musllinux_1_2
            name: "linux arm64 musl"

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: restore timestamps
        uses: chetan/git-restore-mtime-action@v2

      - name: restore timestamps
        uses: chetan/git-restore-mtime-action@v2
        with:
          working-directory: "dprint"

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-key: "${{ matrix.platform.manylinux }}"

      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.platform.target }}
          args: --release --out dist --target-dir=./target/
          manylinux: ${{ matrix.platform.manylinux }}

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.platform.name }}
          path: dist
