name: build wheels

on:
  workflow_call:

jobs:
  linux:
    runs-on: "ubuntu-24.04"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - run: pip install -r requrements.txt
      - run: python build.py

      - uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: dist
